[book]
authors = ["a327ex"]
language = "en"
multilingual = false
src = "src"
title = "𝕭𝖄𝕿𝕮𝕻𝕬𝕿𝕳 𝖉𝖑𝖔𝖌𝖘"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/scillidan/BYTEPATH-blogs"
git-repository-icon = "fa-github"